exHOME=../..
V_BIN=${exHOME}/bin/verilator
DESIGN=${exHOME}/exaVeri/exaDatabase
VERI_HEAD=${exHOME}/include
// VERILATOR_ROOT = /media/regaltos/mark/regaltosMini/dev/verilator/exaVeri/vbin
add : add.cpp ${DESIGN}/add.v
	${V_BIN} --cc -I${VERI_HEAD} --build $^



